### ISSUE TITLE
Cleanup of unused features

### ISSUE THREAD

**Issue by yantosca** [KineticPreProcessor/KPP#19]
@RolfSander has opened the **cleanup** branch, which removes several unused/obsolete files.  We will test to make sure that none of the existing functionality is clobbered.

**Comment by RolfSander** [comment]
Thanks! I hope all the ci-tests are still working. The only change I made is that small_f90 now uses `int/kpp_lsode.*` instead of `int.modified_WCOPY/kpp_lsode.*`.

**Comment by yantosca** [comment]
I just verified that all the CI-tests work properly in the cleanup branch.  See:
[ci-tests-log.txt](https://github.com/KineticPreProcessor/KPP/files/8305057/ci-tests-log.txt)

**Comment by RolfSander** [comment]
I'm not sure if my comment in the pull request was visible, since it is closed now. So I'm repeating it here:

I have a couple of other cleanup-items which I want to do next. I'll
create a new "cleanup2" branch for that. One thing I noticed is that we
have a .gitignore file in almost every directory. That's not necessary
because a .gitignore file in the root directory affects all
subdirectories automatically.

One more minor comment on .gitignore: Some of the files contain the line `#*` which probably should ignore files starting with a hash. However, this doesn't work because lines starting with  `#` are comments in .gitinore. We need to write `\#*` instead, see:

https://stackoverflow.com/questions/2209810/add-glob-to-gitignore

**Comment by RolfSander** [comment]
already merged into dev
