### ISSUE TITLE
[FEATURE REQUEST] Add optional toggle to check if a mechanism needs a minimum KPP version

### ISSUE THREAD

**Issue by yantosca** [KineticPreProcessor/KPP#31]
I was thinking it might be a nice feature to have the ability to add an optional KPP toggle such as `#MINIMUM_REQUIRED X.Y.Z` so that KPP will throw an error unless you are using version X.Y.Z or higher.

For example, the CMake build system lets you specify a minimum version such as:
```cmake
cmake_minimum_required (VERSION 3.13)
```

This might become important for models such as GEOS-Chem where we have many different versions in use.   For example, if someone wanted to use a mechanism with the new `#AUTOREDUCE` capability that @jimmielin and @msl3v are developing, you would need to use KPP 3.0.0 (when it is ready).   But if you don't want to use the #AUTOREDUCE feature then you wouldn't need to specify a minimum version.

I can work on adding this to the add-geos-chem-updates branch.

**Comment by RolfSander** [comment]
Good idea! Two comments:

- I'm not sure how long the command names can be. If #MINIMUM_REQUIRED
  is too long, maybe #MINVER would suffice?

- Make sure that the new command is analyzed first. Otherwise, the code
  could crash at an undefined #AUTOREDUCE command even though you have
  specified a minimum version.

**Comment by yantosca** [comment]
#34 has now been merged into the development branch.  We can close this now.

**Comment by RolfSander** [comment]
Thanks for adding the #MINVERSION feature!
I added two minor commits in dev...
