### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by fhkiwi** [KineticPreProcessor/KPP#58]
# Ask a question about KPP:
Teachers, experts hello! We are having some problems running KPP.
[Some problems about parameter input of KPP model.docx](https://github.com/KineticPreProcessor/KPP/files/9356982/Some.problems.about.parameter.input.of.KPP.model.docx)

**Comment by yantosca** [comment]
Thanks for writing @fhkiwi.  We cannot assist with implementation of KPP into another model or user context, as that is beyond the scope of our expertise.  But we can offer some general advice:

> 1.	In the process of simulating ozone generation using KPP model, we found that only one temperature parameter was entered in the model input file. What if we wanted to input hourly meteorological parameters (such as temperature, relative humidity, atmospheric pressure, and mixed layer height)?

You would need to add those extra variables in the F90_GLOBAL section (so that they get added to the ROOT_Global.F90 file.  You would also need to modify your driver program (e.g. `general.F90`) so that it reads in the data from disk and assigns it to the global variables.

> 2.	In cities, ozone precursors (VOCs, NOx) are emitted from the ground every hour. How can we express the hourly emission rate of precursors?

You would likely need to add a rate law function in the KPP definition file that reads in emissions and passes them to KPP.

> 3.	In the chemical reaction Equations file, we know how to express the rate constants for different reactions. These instructions can be found in "UserRateLaws", but the description of photolysis rate constants is not found.

This is something you would need to add in your own rate law functions.

> 4. How to express the rate law function.

You might need to write your own rate law function for KPP.  You would want to test to make sure that n>0 before doing the division, or else you'd get a division-by-zero error.

Also tagging @RolfSander @jimmielin

**Comment by yantosca** [comment]
Closing out this issue due to inactivity
